### ISSUE TITLE
UX checklist

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#510]
This is a list of ways the UX is confusing and my suggestions for changes. Hopefully we can have most of these changes ironed out.

- [x] Announcing as a host, saving your settings, turning the host on + off, that's currently a confusing process. We can probably fix this by adding a specific switch that says 'accepting new contracts' vs. 'not accepting new contracts'. Also, there should be some indication of how much storage is currently in use, that's not currently available on the UI.
- [x] There seems to be a bug with host settings where after you've announced you can't change how much storage you are offering. At the very least, the UI doesn't ever reflect a change away from 2GB.
- [x] Nicknames don't include the file extension unless you add the extension manually. It should, especially for sharing files.
- [x] Wallet addresses are really confusing because they disappear, and at the beginning it looks like you have no addresses at all. I think it would be easy to fix this by adding some faded text below your address list that says how many addresses total you have.
- [x] It's hard to tell (esp. from the UI) if the miner is working. There should be some indication of hashrate, followed some indication of how that converts to blocks. Example: 1.3Mhash/s, 235 blocks/month. Probably also nice to have some indication of how many blocks total you've found, though that requires checking for orphans.

**Comment by DavidVorick** [comment]
I'm going to call this fixed even though the first item is only partially implemented. It's a lot better than before at least.
